template: main
title: Genereto Documentation
url: https://gh.fponzi.me/genereto
description: Documentation for Genereto static site generator
default_cover_image: ../assets/genereto-logo.jpg

blog:
  base_template: blog.html
  index_name: index.html
  destination: blog/
  title: Genereto Documentation