template: main
title: Genereto Documentation
url: https://gh.fponzi.me/genereto
description: Documentation for Genereto static site generator

blog:
  base_template: blog-index.html
  index_name: index.html
  destination: blog/
  title: Genereto Blog
  default_cover_image: ../assets/genereto-logo.jpg